### ISSUE TITLE
(vector (unsiged-byte 8) (*)) type

### ISSUE THREAD

**Issue by incjung** [tanakahx/cl-binary#1]
First of all, the cl-binary is good at us. Thank you.

Anyway, I have a problem when I load it. I cloned it and tested it.

But when I use a `with-binary-input-stream` method, it could not create a instance of binary-input-stream class because of the type ` (vector (unsiged-byte 8) (*))`

In the code, the class looks like : 
```
(defclass binary-input-stream (fundamental-binary-input-stream)
  ((data :initarg :data :type (vector (unsigned-byte 8) (*)))
   (index :initarg :index)
   (end :initarg :end)))
```

Why don't you use ` '(vector (unsiged-byte 8) (*))`
Perhaps it is typo problem. is it?

**Comment by tanakahx** [comment]
Thanks for letting me know this issue. Also, sorry for the late reply.
Just as you said, it is a vector type specifier bug in the class definition. I have finally fixed it.
